version: '3.8'

services:
  cutemagick:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - sites:/app/sites
      - app-data:/app/data
      - ssh-data:/app/.ssh
volumes:
  ssh-data:
