services:
  app:
    environment:
      - NODE_ENV=development
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./sites:/app/sites
      - ./ssh-data:/app/.ssh
      - ./src:/app/src               # live reload your source code
      - /app/node_modules            # prevent overwriting node_modules
      # REMOVED ./data:/app/data - let it use image files