services:
  app:
    environment:
      - NODE_ENV=development
    build: .
    env_file:
      - .env
    volumes:
      - ./sites:/app/sites
      - ./data:/app/data
      - ssh-data:/app/.ssh
volumes:
  ssh-data:
