services:
  app:
    environment:
      - NODE_ENV=production
    build: .
    env_file:
      - .env
    volumes:
      - sites:/app/sites
      - ssh-data:/app/.ssh
      # REMOVED app-data volume - let /app/data use image files

volumes:
  ssh-data:
  sites:
  # REMOVED app-data