services:
  app:
    environment:
      - NODE_ENV=development
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./sites:/app/sites          # bind mount to local directory
      - ./data:/app/data             # bind mount to local directory
      - ./ssh:/app/.ssh              # bind mount to local directory
      - ./src:/app/src               # live reload your source code
      - /app/node_modules            # prevent overwriting node_modules

# Remove the volumes section entirely for local dev