services:
  app:
    environment:
      - NODE_ENV=development
    build: .
    env_file:
      - .env
    volumes:
      - sites:/app/sites
      - app-data:/app/data
      - ssh-data:/app/.ssh
volumes:
  ssh-data:
  app-data:
  sites: